### ISSUE TITLE
Update `.gitignore` to exclude all user configs

### ISSUE THREAD

**Issue by aaaaalbert** [EdgeNet-project/edgenet-legacy-2024#1]
I think that for redeployability and privacy reasons, our `.gitignore` should be set to exclude from `user_files/yml/*` all the files that are neither templates nor required by the system.

As far as I can tell, Git should only track
* `rb -template.yml`
* `role-template.yml`

and probably the `kube-system-*.yml` ones.

@m-hemmings, does this suffice to yield a system for which new users can later be added?

**Comment by tashabits** [comment]
I agree, I'll look into what can be done to exclude the mentioned files

**Comment by aaaaalbert** [comment]
Thank you!

(Independent of the `.gitignore`, we might want to move templates to a separate dir altogether, just so that #4 doesn't bite us for users trying names like `template`...)

**Comment by tashabits** [comment]
Added a template directory ( dbac6555a923a54fb65c3a623180322864a036ec ), moved template files ( 03c6a2b93ee06b4e76d1c39de25c5fb840c3e3ef ), updated gitignore and untracked user configs ( b3e3e8dd6663d03e6a17a7c10d143f6cf8a32dd0 ce95c30c03f25264483c01b41e75d08852e97896 )
