### ISSUE TITLE
Need a beefier head node

### ISSUE THREAD

**Issue by rickmcgeer** [EdgeNet-project/edgenet-legacy-2024#11]
Even with 6 nodes, the head node is crawling to a stop.  Investigate, in order:
Chameleon
Jetstream
Google
Azure
AWS

For commercial services, we should investigate a freebie

**Comment by tashabits** [comment]
UVic has provided a head node for us, we're just waiting on ports to be opened before I can start transition of head node to this site.

**Comment by tashabits** [comment]
Ports are opened, I have begun the transition to the new head node.  Will swap over when it's finished

**Comment by aaaaalbert** [comment]
Quoting from the conf call, this is a 4-core machine with 16 GiB of RAM which should scale to around 100 nodes.

**Comment by tashabits** [comment]
Documentation I've been using as a guideline can be found [here](https://kubernetes.io/docs/admin/cluster-large/)

**Comment by tashabits** [comment]
Confirmed restart with nodes after shutdown, good step

**Comment by aaaaalbert** [comment]
Awesome news, thank you!
