### ISSUE TITLE
Enable an "EdgeFlow" service

### ISSUE THREAD

**Issue by timur-friedman** [EdgeNet-project/edgenet-legacy-2024#116]
EdgeFlow is the name that we give to a feature that will be essential for accountability on EdgeNet. It will provides NetFlow-style packet header capture at each EdgeNet worker node, thereby allowing people to determine who was responsible for any packet that entered or left EdgeNet. The concept is based the PlanetFlow service that ran on PlanetLab.

EdgeFlow will register the "five-tuple" of each packet that leaves or enters each EdgeNet worker node: source IP address, source port number, destination IP address, destination port number, and transport-layer protocol. It will associate the five-tuple with the pod that is the ultimate source or destination for the packet, thereby allowing an association with the owner of the pod.

This "flow data", in the IPFIX (or NetFlow or sFlow) format, will be gathered on the worker node. Ultimately, it will need to be made available to concerned third parties that have witnessed unusual traffic. This can be done in two ways: via a website run on TCP port 80 of the worker node, or via a website run centrally by the EdgeNet administrators. 

Based upon our experience running PlanetFlow on PlanetLab Europe, some combination of the two ways of presenting the EdgeFlow data is probably needed. Network administrators who witness unusual traffic will naturally look to the IP address at the source of that traffic, so a website on a worker node provides a first line response. But queries might also come to the EdgeNet administrators themselves, for whom a centralized database allows answers to be found, even when the worker node in question is no longer accessible (provided that it previously had time to offload its data).

**Comment by timur-friedman** [comment]
[This talk](https://www.youtube.com/watch?v=sj7pmz5sutE) by [Rastislav Szabo](https://www.linkedin.com/in/rastislavs/) of [PANTHEON.tech](https://pantheon.tech/) appears to be highly pertinent.

[Szabo points out](https://youtu.be/sj7pmz5sutE?t=520) that in a Kubernetes deployment, the entity that plays a similar role to a router or a switch is a CNI plugin. It routes or switches the nodes between the pods on a given node, as well as between nodes. This is where the flow data can be captured.

For collection and analysis of the flow data, [he suggests](https://youtu.be/sj7pmz5sutE?t=575) an [ELK stack](https://www.elastic.co/what-is/elk-stack): Elasticsearch, Logstash, and Kibana. Logstash, the part that does the collection, supports IPFIX, NetFlow, and sFlow. Elasticsearch, which does the storage part, can be used for searching through the flows. Kibana can be used for analysis.

[The CNI in which Szabo has enabled IPFIX](https://youtu.be/sj7pmz5sutE?t=638) is Contiv-VPP. It is based on the [FD.io](https://fd.io/) VPP vSwitch as the data plane. [Contiv-VPP](https://contivpp.io/) supports IPFIX, and it just needs to be enabled, says Szabo. [Here is](https://docs.fd.io/vpp/18.11/ipfix.html) a note on configuring FD.io to export IPFIX records.

In another talk, [Szabo relates](https://youtu.be/ICi1SEX4NJ0?t=735) how, between pods on the same node, Contiv-VPP uses memif shared memory for packet forwarding. Between pods on different nodes, [DPDK](https://www.dpdk.org/).

Szabo describes how he uses Contiv-VPP, Ligato, and FD.io to generate the IPFIX data, and then a specially adapted ELK stack for IPFIX called [ElastiFlow](https://github.com/robcowart/elastiflow) to receive and process the data.

**Comment by timur-friedman** [comment]
@bsenel which CNI do we currently use for EdgeNet?

**Comment by bsenel** [comment]
We use [Weave Net](https://kubernetes.io/docs/tasks/administer-cluster/network-policy-provider/weave-network-policy/) as CNI plugin.

**Comment by timur-friedman** [comment]
OK, I see that Weave does not currently permit the collection of IPFIX/NetFlow/sFlow statistics:

https://github.com/weaveworks/weave/issues/3596

We should think about whether we can adopt Contiv-VPP in place of Weave.

**Comment by timur-friedman** [comment]
@cscognamiglio @rickmcgeer @JustinCappos @eqfarhad @habdullah 

Kindly take a look, we'll discuss tomorrow.

**Comment by timur-friedman** [comment]
Following discussion with people at Cisco who have developed an FD.io VPP data plane for the Calico networking technology, we will try using the Calico CNI in place of the Weave CNI. If it works, we can envisage building on this for our EdgeFlow solution.

Notably, the folks at Cisco have already developed an [IPFIX exporter](https://git.fd.io/vpp/tree/src/plugins/flowprobe) for the [Calico VPP data plane](https://github.com/projectcalico/vpp-dataplane). Our contacts at Cisco suggest two ways in which we could build upon this:

1. Simultaneously collect the IPFIX flow data and the Kubernetes logs that describe the IP address of each container and associate the two.
1. Extend the IPFIX exporter to attach metadata concerning which container is at the origin of each packet.

**Comment by timur-friedman** [comment]
We should look into the current status of IPv6 in Kubernetes and plan accordingly.

**Comment by bsenel** [comment]
I've googled the issue so there seem to be a few steps to go from Weave to Calico. And these might cause some downtime due to the cluster configuration.

First of all, all Kubernetes objects related to Weave need to be deleted, which is so easy. Next, we need to clear all files related to Weave configuration and binaries and remove the Weave interface from the nodes. At this point, the EdgeNet cluster is ready to install Calico.

I will share the results when I make this transition in the sandbox.

**Comment by bsenel** [comment]
I am happy to announce that Calico has officially replaced Weave in production. 🥳
