### ISSUE TITLE
Revamped access control

### ISSUE THREAD

**Issue by timur-friedman** [EdgeNet-project/edgenet-legacy-2024#117]
EdgeNet's access control mechanism is based on namespaces.

Currently, there are four namespace schemas:

1. Authorities -> `authority-<authority name>`
2. Slices in an authority -> `authority-<authority name>-slice-<slice name>`
3. Teams -> `authority-<authority name>-team-<team name>`
4. Slices in a team -> `authority-<authority name>-team-<team name>-slice-<slice name>`

The proposal is to make the mechanism more readily understandable to Kubernetes users, who already understand that namespaces are a way to divide a cluster's resources amongst users, with resource quotas allocated to each namespace. They will not so readily grasp the names Authority, Team, or Slice.

The new namespace schema would look like this:

1. top level namespace: `<top level name>`
2. subsidiary namespace : `<top level name>-<subsidiary name>-...-<subsidiary name>`

Where there can be as many levels as desired, providing the maximum name length is not exceeded. The names at each level would be separated by dashes, and could not themselves contain dashes.

Terminology would change in the following manner:
- Rather than saying "register an authority", we would say "register a top level namespace".
- Rather than saying "create a slice", we would say "create a subsidiary namespace".
- Rather than saying "create a team", we would also say "create a subsidiary namespace".

Users could sign up to, or be signed up to, a top level namespace or a subsidiary namespace. For example, if a subsidiary namespace represents a university class, the students of that class could be signed up to the class's namespace and not to the university's namespace. In so doing, we can more easily restrict the visibility that students have into the university's EdgeNet account. We could also more easily invalidate the student accounts when their class ends.

With OPA, we could define the following sorts of permissions for a namespace:
- To set/update the resource quota
- To create deployments/daemon-sets/etc.
- To list the users and/or subsidiary namespaces and/or node contributions
- To create/update/delete users and/or subsidiary namespaces and/or node contributions
- To enable/disable any of the permissions for another user (a user belonging to the namespace or a parent of the namespace, or a user belonging to a namespace outside of that hierarchy)

We could also define the following roles:
- Lead users for a namespace (the ones responsible for the use of that namespace), who will have certain permissions by default
- Administrator of a namespace, who receives e-mails relating to the permissions, and who can be a lead user or someone designated by the lead user

Terminology would change with regards roles:
- Rather than saying "authority admin", we would say "lead user of a top level namespace".
- Rather than saying "team manager", we would say "administrator of a subsidiary namespace".

The lead user of a namespace would be able to decide on a flat namespace or as many levels of hierarchy as they deem useful, according to their needs.

Some namespaces, notably those that just contribute nodes, would not have deployment creation permissions associated with them.

The web console would give vision into a given namespace, the ability to take relevant actions on that namespace, and the possibility of navigating up or down, as allowed, in the namespace hierarchy.

**Comment by timur-friedman** [comment]
@bsenel, I've written out a proposal based upon what we were discussing today.

**Comment by timur-friedman** [comment]
@cscognamiglio @rickmcgeer @JustinCappos @eqfarhad @habdullah 

Kindly take a look. We'll discuss tomorrow.

**Comment by junekiwi** [comment]
@timur-friedman @bsenel is this still relevant?
