### ISSUE TITLE
Update installation of required packages in Node Contributions

### ISSUE THREAD

**Issue by bsenel** [EdgeNet-project/edgenet-legacy-2024#143]
There is a malfunction of installing the required packages such as Docker and Kubernetes at the node contribution. 

## Acceptance Criteria

- Following the official instructions, e.g. [Docker](https://docs.docker.com/engine/install/), [Kubernetes](https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/install-kubeadm/). 
- The way of running command through the SSH client needs to be adapted to provide more feedback about the results.
- Provide a shell script that prepares an SSH user, does the installation, and communicates with the EdgeNet API via a token to create a node contribution object.
- The installation procedure should setup the OS firewall, allowing common ports and [k8s ports](https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/install-kubeadm/#check-required-ports).

### Backend:
- [ ] Update the installation procedures in the [controller](https://github.com/EdgeNet-project/edgenet/blob/master/pkg/controller/v1alpha/nodecontribution/handler.go)
- [ ] Improve the way of running commands through the SSH client
- [ ] Develop a shell script
- [ ] Code error handling

**Comment by junekiwi** [comment]
Done in https://github.com/EdgeNet-project/node
