### ISSUE TITLE
Rename `test1.py`

### ISSUE THREAD

**Issue by aaaaalbert** [EdgeNet-project/edgenet-legacy-2024#15]
[`test1.py`](https://github.com/aaaaalbert/sundew-one/blob/f8825a08a5628046e91e3bc2850202da6931e179/test-portal/test1.py) is actually the Google App Engine web app. Its filename should be changed accordingly.

**Comment by aaaaalbert** [comment]
Also, the `test_portal/` dir should perhaps be renamed to `portal/`.

**Comment by rickmcgeer** [comment]
OK, thanks.  Do you know how to rename files without doing something violent to git?

**Comment by aaaaalbert** [comment]
It's a pure mechanical `git mv SOURCE DEST`, nothing fancy really.

I worried more about dependencies that I'm unaware of (`usgi`? GAE?), so I chose not to do it.

**Comment by rickmcgeer** [comment]
Done, and I took care of the dependencies, and thanks, Albert.  You knew the github stuff, I knew the dependencies...if only one of us knew both!  Cheers and thanks.

**Comment by aaaaalbert** [comment]
My pleasure! Fixed in b7a6e83abe460ec89ad4263719573a859ae1a1ae, just for reference.
