### ISSUE TITLE
Enable IPv6 Support

### ISSUE THREAD

**Issue by bsenel** [EdgeNet-project/edgenet-legacy-2024#166]

**Comment by junekiwi** [comment]
### Status as of July 2022

- Private IPv6 networking over the IPv4/v6 Internet is provided by the Wireguard VPN mesh:
```bash
edgenet@geni---64e9:~$ ip addr show edgenetmesh0
3: edgenetmesh0: <POINTOPOINT,NOARP,UP,LOWER_UP> mtu 1420 qdisc noqueue state UNKNOWN group default qlen 1000
    link/none 
    inet 10.183.13.215/20 brd 10.183.15.255 scope global edgenetmesh0
       valid_lft forever preferred_lft forever
    inet6 fdb4:ae86:ec99:4004::ab7:dd7/64 scope global 
       valid_lft forever preferred_lft forever
```

```bash
edgenet@geni---2493:~$ ping6 fdb4:ae86:ec99:4004::ab7:dd7
PING fdb4:ae86:ec99:4004::ab7:dd7(fdb4:ae86:ec99:4004::ab7:dd7) 56 data bytes
64 bytes from fdb4:ae86:ec99:4004::ab7:dd7: icmp_seq=1 ttl=64 time=24.7 ms
64 bytes from fdb4:ae86:ec99:4004::ab7:dd7: icmp_seq=2 ttl=64 time=25.0 ms
64 bytes from fdb4:ae86:ec99:4004::ab7:dd7: icmp_seq=3 ttl=64 time=24.9 ms
64 bytes from fdb4:ae86:ec99:4004::ab7:dd7: icmp_seq=4 ttl=64 time=24.8 ms
```

- Some GENI nodes do not support IPv6: we cannot assign an IPv6 address to an interface. Hypervisor limitation?

### Next steps

- Configure Kubernetes to assign IPv6 addresses to the pods
  - Update `clusterCIDR` in the `kube-proxy` ConfigMap.
  - Update `pod-network-cidr` in the `kubeadm-config` ConfigMap.
  - Update `--cluster-cidr` in `/etc/kubernetes/manifests/kube-controller-manager.yaml` on the control plane nodes.
- Enable IPv6 forwarding on the host to reach the IPv6 Internet on nodes with IPv6 connectivity.
  - Set `net.ipv6.conf.all.forwarding=1` in the Ansible `edgenet-kubernetes` role.

### References
- https://kubernetes.io/blog/2021/12/08/dual-stack-networking-ga/
- https://kubernetes.io/docs/concepts/services-networking/dual-stack/#enable-ipv4-ipv6-dual-stack

**Comment by junekiwi** [comment]
---
