### ISSUE TITLE
Make this repo public

### ISSUE THREAD

**Issue by aaaaalbert** [EdgeNet-project/edgenet-legacy-2024#17]
I think there isn't much to gain in keeping this repository private.

Are there any objections to letting the world see it, and the ~~~~Sundew~~~~ ~~~~edgeNet~~~~ Edge-Net Github organization own it?

**Comment by tashabits** [comment]
None from me, nope

**Comment by aaaaalbert** [comment]
Thanks. How about @rickmcgeer?

**Comment by aaaaalbert** [comment]
We agreed in today's conf call to make the repo public and transfer ownership to the @EdgeNet-Project organization.

I'll see you on the other side 😉
