### ISSUE TITLE
README "architecture document" is a broken link

### ISSUE THREAD

**Issue by remram44** [EdgeNet-project/edgenet-legacy-2024#178]
There is no branch `release-1.0-documentation` so it's 404: https://github.com/EdgeNet-project/edgenet/tree/release-1.0-documentation/docs/architecture

Maybe change it to https://github.com/EdgeNet-project/edgenet/tree/release-1.0/docs/architecture?

**Comment by remram44** [comment]
On the other hand, most of the links in the document itself are also broken, so maybe this project is just dead.

**Comment by ubombar** [comment]
Hi, @remram44, thanks for opening an issue. We are working on extensive documentation at this moment. You can find it in the [ufukbombar-docs](https://github.com/EdgeNet-project/edgenet/tree/ufukbombar-docs) branch.

Open-source projects are usually slow-paced. If you want to contribute, feel free to refer to the new documentation 😊.
