### ISSUE TITLE
Add setup script and instructions

### ISSUE THREAD

**Issue by aaaaalbert** [EdgeNet-project/edgenet-legacy-2024#2]
We should think about adding a setup script to ease (re)deployment, and also document the steps needed to get the thing running.

**Comment by tashabits** [comment]
Temporary setup instructions for a cluster are [here](https://docs.google.com/document/d/1Z_C3tUC_YwGW0g2Y9NrwNMEAiiNdqd4Rh1Bh9F6Vty4/edit#heading=h.hmzr233u9asb), but I would like to use the step over to the new head node to validate them before I publish them properly

**Comment by aaaaalbert** [comment]
Dependencies for the Flask part:
* python3
* pip3
* flask
* pyOpenSSL

**Comment by aaaaalbert** [comment]
The Google doc for the headnode looks good to me. Let's make a Markdown doc out of it.
