### ISSUE TITLE
Design strawman logo and page template

### ISSUE THREAD

**Issue by rickmcgeer** [EdgeNet-project/edgenet-legacy-2024#22]

**Comment by rickmcgeer** [comment]
Got to replace the PlanetIgnite logo on the main page. An initial cut is in https://docs.google.com/drawings/d/1oQVVtSamdBV7e8rGWtbTYN2SOIv6ycimdzDB8lc3mFk/edit?usp=sharing. The issue will be closed when we are happy with it or with a better one.

**Comment by JustinCappos** [comment]
I think it's a fine placeholder.  After we get to a MVP and have a community, we can have a contest for a more permanent logo.

**Comment by rickmcgeer** [comment]
Closed for now, then
