### ISSUE TITLE
Fix hardcoded paths in configs and sources

### ISSUE THREAD

**Issue by aaaaalbert** [EdgeNet-project/edgenet-legacy-2024#3]
In connection to #2, we must change a few paths in the various configuration files and sources so that the developers' home directories etc. are no longer hardcoded. Grep-dash-i for `/users/` to see what I mean.

**Comment by tashabits** [comment]
If that's a reference to the supervisor file, I am not finished with that for a completely different reason, which is that supervisor seems to not terminate the server on request or be able to restart it on abnormal termination.  Is there another one I missed?

**Comment by aaaaalbert** [comment]
I saw Rick's home dir somewhere too. No big deal, this issue is really just a reminder to keep things neat and clean.

**Comment by aaaaalbert** [comment]
The GitHub search form also identifies the three relevant occurrences:
https://github.com/aaaaalbert/sundew-one/search?utf8=%E2%9C%93&q=users&type=

**Comment by tashabits** [comment]
Removed supervisor file in 79b5d8ea0931b344d6e13b4fa0522d60983202c3

**Comment by aaaaalbert** [comment]
See also 9deebde1be693fa5ca67fb087691d857a29a276b for an instance.

**Comment by tashabits** [comment]
Noted in the commit comments, I will fix it by passing the key and cert in as arguments during launch.  I like the idea better than a fixed config file

**Comment by rickmcgeer** [comment]
Is this still open?
