### ISSUE TITLE
Remove errors on entry to dashboard

### ISSUE THREAD

**Issue by rickmcgeer** [EdgeNet-project/edgenet-legacy-2024#31]
Currently, this is the first screen I see as a user, with a bunch of error messages at the top.  I should see something clean...
![screen shot 2018-05-28 at 7 30 24 am](https://user-images.githubusercontent.com/656259/40619211-0fd2a6b4-6249-11e8-8d00-b5b87eca27ef.png)

**Comment by tashabits** [comment]
Errors remain, but namespace box now populates and lists namespaces on entry.  Errors as shown are correct, as they indicate actions you cannot take in the namespace you are currently in.  If that is a problem, we may need a new dashboard.  Please advise and close if this resolves your issue. ba16607f4f64286a76eedfd912840b12a81d65d7
