### ISSUE TITLE
errors when I click on "Nodes"

### ISSUE THREAD

**Issue by rickmcgeer** [EdgeNet-project/edgenet-legacy-2024#32]
Same issues as in login, which, when I expand them, shows this...users need to be able to see the nodes
![screen shot 2018-05-28 at 7 32 12 am](https://user-images.githubusercontent.com/656259/40619314-702fd176-6249-11e8-9ce4-62c3e4984010.png)

**Comment by tashabits** [comment]
Nodes are now viewable for all users.  Workloads continue to be invisible by design. ba16607f4f64286a76eedfd912840b12a81d65d7
