### ISSUE TITLE
Support other shells than Bash in setup_node.sh

### ISSUE THREAD

**Issue by tashabits** [EdgeNet-project/edgenet-legacy-2024#34]
This is a bash only script, this needs to be adjusted

**Comment by aaaaalbert** [comment]
Link to file: https://github.com/aaaaalbert/sundew-one/blob/master/daemons/setup_node.sh

**Comment by junekiwi** [comment]
Not relevant anymore; see https://github.com/EdgeNet-project/edgenet/pull/144.
