### ISSUE TITLE
setup_node.sh turns off system swapping

### ISSUE THREAD

**Issue by EricAllman** [EdgeNet-project/edgenet-legacy-2024#35]
The `setup_node.sh` script turns off virtual memory swapping (using `swapoff -a`) and never turns it back on again.  I assume this has something to do with making sure that `$SECRET` doesn't leak any information, but it does leave the system in a potentially different state after running the script.

**Comment by tashabits** [comment]
This is actually not a bug, exactly.  As per this issue:
https://github.com/kubernetes/kubernetes/issues/53533
Swap is not supported on worker nodes.  I am monitoring that for a fix if it's implemented, but for how this is the reason swap is disabled.
