### ISSUE TITLE
Several people have namespace status == REQUESTED

### ISSUE THREAD

**Issue by rickmcgeer** [EdgeNet-project/edgenet-legacy-2024#38]
This is supposed to be transient.  It means a namespace has been requested but not assigned by the head node.  One of two things can be going on:

(1) The daemon on the head node isn't calling back the portal
(2) The assignment of the namespace failed for some reason

In any case, we can't have users in limbo forever.  We need to troubleshoot this...

**Comment by rickmcgeer** [comment]
Portal now queries the headnode and renews request every 10 minutes until satisfied.

**Comment by aaaaalbert** [comment]
Code cross-references:
* `UpdateConfigs` request handler that does the request to the headnode) --- https://github.com/EdgeNet-project/portal/blob/15646a5ea3925a1bbfef255a3df6c5522bbfac00/portal.py#L739
* the cronjob that re-requests --- https://github.com/EdgeNet-project/portal/blob/75cc88f60960a32b418a5e70c27830be0a14de5a/cron.yaml#L9-L14

@rickmcgeer, please note that the cronjob is currently set to **30 minutes**, not ten as you suggested.
