### ISSUE TITLE
Dashboard timing out rapidly

### ISSUE THREAD

**Issue by rickmcgeer** [EdgeNet-project/edgenet-legacy-2024#39]
I am continually forced to log in again, and given that I also have to manually type in the namespace before I can do anything this is really annoying.  Can we change the timeout interval?

**Comment by tashabits** [comment]
Default timeout is 15 minutes, do you need longer than that? If so, what time would you like?

**Comment by tashabits** [comment]
@rickmcgeer requested 2 hour timeout, this has been updated
