### ISSUE TITLE
Sanitize user input from HTTP headers

### ISSUE THREAD

**Issue by aaaaalbert** [EdgeNet-project/edgenet-legacy-2024#4]
It looks like we construct commands [to be `Popen`ed from Python](https://github.com/aaaaalbert/sundew-one/blob/e08caea2e3611ff53321feac7d984c47c6929c99/daemons/user-daemon.py#L11-L12) or [dolllar-substituted in shell scripts](https://github.com/aaaaalbert/sundew-one/blob/0b45f8628891ebebac46193bc6ebbf317a687693/user_files/scripts/make-user.sh#L9) from HTTP header field values. This can lead to code injection, overwrite our template configs, and other nastiness.

Any user input we receive and plan to use in the above ways must be sanitized beforehand. [Here](https://github.com/SeattleTestbed/custominstallerbuilder/blob/7c5fc06783a23507adf8373c46e0d3a33812d193/common/validations.py#L169-L198) is an example how we do this in @SeattleTestbed.

**Comment by tashabits** [comment]
Agreed, this is a good idea.  In addition, there will be a configuration on the nginx side that prevents calls to the flask server from anyone but the portal, but I agree that both should be in place

**Comment by tashabits** [comment]
What sort of constraints do we want to place on usernames? Kubernetes imposes a restriction of using only lowercase characters and dashes, and since we were using email addresses, I'm not sure we can guarantee lengths...can you think of anything else?

**Comment by aaaaalbert** [comment]
(I vaguely remember that in Kubernetes, lengths are limited too.)

The obvious restriction is that there must not be a user of this name already, like `template` which currently is guaranteed to be in use.

**Comment by aaaaalbert** [comment]
BTW, since `@` and `.` in email addresses are converted to `-` for user names, there are fun ways to create collisions: E.g. register a domain `mcgeer-us-ignite.org`...
