### ISSUE TITLE
Create button requires page refresh

### ISSUE THREAD

**Issue by rickmcgeer** [EdgeNet-project/edgenet-legacy-2024#40]
When I hit Create, the Resource Creation banner shows but I don't get the wizard.  When I hit page refresh it works
![screen shot 2018-07-29 at 12 03 10 pm](https://user-images.githubusercontent.com/656259/43369716-74fdae08-9327-11e8-853f-2f87ea016131.png)

**Comment by junekiwi** [comment]
Seems OK with the current setup.
