### ISSUE TITLE
Deploy Button on App Creation Wizard doesn't work

### ISSUE THREAD

**Issue by rickmcgeer** [EdgeNet-project/edgenet-legacy-2024#41]
![screen shot 2018-07-29 at 12 05 18 pm](https://user-images.githubusercontent.com/656259/43369738-cc8a195e-9327-11e8-8212-fce28273a785.png)

See attached screenshot.  No matter what I do, I can't get the thing to enable deployment

**Comment by junekiwi** [comment]
Seems OK with the current setup.
