### ISSUE TITLE
kind: Pod not recognized by Dashboard

### ISSUE THREAD

**Issue by rickmcgeer** [EdgeNet-project/edgenet-legacy-2024#42]
Kubernetes claims that kind: Pod is valid (see, for example, https://kubernetes.io/docs/reference/kubectl/cheatsheet/) but the Dashboard doesn't recognize it
![screen shot 2018-07-29 at 12 08 18 pm](https://user-images.githubusercontent.com/656259/43369766-4a520b76-9328-11e8-96a4-500899fe588d.png)

**Comment by tashabits** [comment]
Looks like you're using the v1beta1 apiversion, can you try with v1?  Or attach the file and I will
