### ISSUE TITLE
Needs to be a way for a user to specify which nodes he runs on

### ISSUE THREAD

**Issue by rickmcgeer** [EdgeNet-project/edgenet-legacy-2024#44]
According to the Kubernetes documentation, this involves creating a label, but there seems to be no way to do it from the Dashboard.  And user can't even list the nodes to see which ones to label.  At the moment he has two options: Deploy a Service (Kubernetes chooses) or a DaemonSet (all)

**Comment by aaaaalbert** [comment]
`kubectl get nodes` lists all of our nodes.

There's also a `--field-selector` option for this function that allows to filter for properties. Perhaps this is good enough as a selection method for now.

**Comment by tashabits** [comment]
For now, you can run this from the headnode to label (obviously requires cluster admin access, but running from the head node itself will get you that):
kubectl label nodes toronto-core.edge-net.io toronto.edge-net.io waterloo.edge-net.io region=canada

And this to remove it again:
kubectl label nodes toronto-core.edge-net.io toronto.edge-net.io waterloo.edge-net.io region-

I'll add those to the flask server so the portal can send a list of nodes and labels to have them created and removed

**Comment by bsenel** [comment]
We now have node labeler and selective deployment, at least Alpha versions!
