### ISSUE TITLE
Need a way to share popular ports

### ISSUE THREAD

**Issue by rickmcgeer** [EdgeNet-project/edgenet-legacy-2024#45]
An important use case is distributed services, which means that many people will want to access popular ports.  Currently, users just grab ports and get them or they don't.  Here is one strawman idea:
1. Develop and deploy an nginx DaemonSet that will grab ports 80, 81, 88, 8080, 8081, 8888, 9001,...
2. Create idea of a "slice" which is in a namespace.  When a user wants one of these ports, he creates a slice on the _portal_.
3. Every 10 minutes, the nginx service on each node wakes up, calls the portal, and requests the current slice set.  It then sets up the forwarding rules appropriately for the containers (note it will need the container names associated with the slice as well)

**Comment by JustinCappos** [comment]
What mechanisms exist and are easy to use?  Can you cause a container to be restricted to a set of ports?  (We used this in Seattle and then pre-assigned ports to containers.  It really isn't the best mechanism, but was enough to get us started.)

**Comment by aaaaalbert** [comment]
I've documented a few possible solutions previously: [Port Contention And Service Multiplexing](https://github.com/EdgeNet-project/notes/blob/master/portcontention.md). IPv6 is probably the least nasty one, implementation-wise. It's less convenient for folks on v4-only ISPs though.

What we could need is a requirements list from the different stakeholders involved: experimenters, node operators, platform operators, network admins.

Assigning random ports in @SeattleTestbed worked up to the point that it was impossible (without custom extensions) to run services on well-known ports. Do we think this makes sense for EdgeNet too?

Random find: `nginx` can proxy TCP and UDP to some extent, https://docs.nginx.com/nginx/admin-guide/load-balancer/tcp-udp-load-balancer/

**Comment by aaaaalbert** [comment]
To summarize our discussion during the meeting:

* Go for IPv6, give experimenters separate addresses and DNS names so transport-layer ports never clash
* If IPv4-only, use `nginx`'s proxying mechanisms
* Focus on the common use case, assumed to be IPv4+HTTP right now

If experimenters absolutely need more sophisticated demultiplexing, let's involve them to build the tech for it.

Agree?
