### ISSUE TITLE
Mismatch between dns and headnode

### ISSUE THREAD

**Issue by rickmcgeer** [EdgeNet-project/edgenet-legacy-2024#48]
The headnode has a "gpo" registered, but there is no gpo.edge-net.io in the namecheap database.  There is one in the portal DB, so this indicates that the problem is in updating namecheap.

The way this is supposed to work is that the headnode worker list is ground truth, and the portal db and namecheap are driven from that.  Since we're pushing to gpo, this means that the headnode has gpo as a worker.  So what's going on is the flask server isn't updating namecheap properly.  This is done at the request of the portal, so either the portal isn't querying or the flask server is failing to do the right thing.  ATM I don't know which.

**Comment by rickmcgeer** [comment]
I've been investigating this.  gpo and clemson are worker nodes that aren't in the DB/DNS.  There are two gpo nodes [u'gpo-exo', u'gpoexo11'] which are in the DB/DNS but aren't workers.  Presumably this is a result of a mangled node-add.  Unfortunately, it isn't just a matter of patching the DB/DNS because we don't know the IP addresses of the worker nodes which aren't in the DB.  Further, kubectl get node gpo.edge-net.io -o wide is showing a blank for External IP, so how we get the IP is a good question if it isn't in the DB

**Comment by junekiwi** [comment]
Closing this @rickmcgeer as I think it's not relevant anymore :-)
