### ISSUE TITLE
Sanitize user input from AUP HTTP form

### ISSUE THREAD

**Issue by aaaaalbert** [EdgeNet-project/edgenet-legacy-2024#5]
**If I interpret it correctly** (which is a big "if"!), we trust the user to not muck about with form contents before [`POST`ing the AUP form](https://github.com/aaaaalbert/sundew-one/blob/b69810f2afbbf5e5a1fdc05dc2568aede893489f/test-portal/aup.html#L9-L12). We should not trust them, instead the form must not allow one user to (un)set AUP consent for another user or do other funny things by submitting a faux email address.

To engineer around this, let's use Flask's user session handling (which we presumably do already), and not move data into untrusted territory and back.

**Comment by rickmcgeer** [comment]
email address now taken from Google login, not hidden variable from form

**Comment by aaaaalbert** [comment]
Thanks!

For reference, the fix is in commit f5750ef62cd098239448adab02cb3f1c74ba4358.

**Comment by rickmcgeer** [comment]
Well, we can't use Flask's session handling, because we aren't using Flask.  However, user is now read from the Google login, not from the form.

**Comment by aaaaalbert** [comment]
Fine, then let's remove those parts of the form.
