### ISSUE TITLE
Create service to restart downed nodes

### ISSUE THREAD

**Issue by tashabits** [EdgeNet-project/edgenet-legacy-2024#51]
When nodes go down, we need to connect to them and restart the kubelet service with the correct hostname.  Write a script to do this

**Comment by aaaaalbert** [comment]
Is there a way we can use Kubernetes for this? This sounds much like the kind of task it is supposed to automate, and would be a good opportunity to try some of our own "dogfood".

**Comment by tashabits** [comment]
The node itself comes back up as intended, but if the hostname at the time of restart differs from the name of the node (probably does) then kubelet refuses to register it. 
To resolve currently, you have to go to the node, change the hostname to match the one on the headnode and restart the registration service.  That was the intent of the script.

**Comment by junekiwi** [comment]
Node recovery and hostname fix are implemented in https://github.com/EdgeNet-project/edgenet/pull/144.
