### ISSUE TITLE
Debug Flannel errors on some nodes

### ISSUE THREAD

**Issue by aaaaalbert** [EdgeNet-project/edgenet-legacy-2024#54]
The communication between the headnode and some worker nodes is broken. Using the Dashboard, deploying pods on these nodes yields an error message similar to this:

```
Failed create pod sandbox: rpc error: code = Unknown desc =
NetworkPlugin cni failed to set up pod "hello-world9-27h68_univie"
network: open /run/flannel/subnet.env: no such file or directory
(combined from similar events): error determining status: rpc error:
code = Unknown desc = Error: No such container:
f263fbeaac4a4f01f4b75fabb85ae71838a93b5b5c98fe7683eaffeffeb7b81e
```

Trying to get the `log` off such pod or `exec -ti` stuff through `kubectl` times out after a while.

**Comment by aaaaalbert** [comment]
I already have logins on our nodes that run on GENI. @rickmcgeer and @m-hemmings, please add my SSH key on the portal, headnode (if not on GENI anyway), and ideally the Toronto EdgeNet nodes too -- the latter so that I have known-working nodes to compare to. Thanks!

**Comment by aaaaalbert** [comment]
Done that, thank you again. I'll start to investigate.

**Comment by aaaaalbert** [comment]
Findings so far:
* `kubectl describe nodes` reveals that *most* nodes have a public IPv4 address as their `InternalIP`. Only the Toronto nodes and Carleton and Waterloo (and Node-0) have a 10/8 address; Sundew-Project is on a 172.16/20.
* `kubectl get nodes -o wide` shows that most nodes run Ubuntu 16.04.1 currently. Only those nodes with private IP addresses run something else, mostly 16.04.4.

**Comment by aaaaalbert** [comment]
On the four worker nodes that I can `ssh` into, those that exhibit the error indeed lack the file `/run/flannel/subnet.env` that the error message mentions.

**Comment by aaaaalbert** [comment]
@m-hemmings mentions that he added 10/8 on Carleton and Waterloo, so that's why they had these addresses.

**Comment by aaaaalbert** [comment]
Possibly related reading:
* "NetworkPlugin cni failed to set up pod network: open /run/flannel/subnet.env error with using tag 2.2.0", https://github.com/kubernetes-incubator/kubespray/issues/1764
* "User "system:node:127.0.0.1" cannot get configmaps in the namespace "kube-system".: "no path found to object" (mentions `hostname` issues), https://github.com/kubernetes/kubernetes/issues/49880
* "NetworkPlugin cni failed to set up pod network: open /run/flannel/subnet.env error with using tag 2.2.0" (also about hostnames), https://github.com/kubernetes-incubator/kubespray/issues/1764
* "Kubernetes CNI errors with flannel on container init (network: open /run/flannel/subnet.env: no such file or directory")", https://github.com/kubernetes/kops/issues/2755
* "Kubelet starts pods before CNI is configured", https://github.com/kubernetes/kubernetes/issues/43014

**Comment by aaaaalbert** [comment]
I had a hard time figuring out what's going on from the (few) logs (that I could find), so instead I went to see how the flannel setup is supposed to work.

First, [our headnode installation instructions](https://github.com/EdgeNet-project/headnode/blob/master/INSTALL.md#headnode-kubeadm-dashboard-flannel) apply the `kube-flannel` Kubernetes config. This config includes (amongst other things) a `DaemonSet` named [`kube-flannel-ds-amd64`](https://github.com/coreos/flannel/blob/c5d10c8b16d7c43bfa6e8408673c6d95404bd807/Documentation/kube-flannel.yml#L82-L159) that is replicated across all of our nodes.

Each pod is based on an [Alpine Linux image with `flanneld`](https://quay.io/coreos/flannel:v0.10.0-amd64). The config does multiple things:

* It [mounts](https://github.com/coreos/flannel/blob/c5d10c8b16d7c43bfa6e8408673c6d95404bd807/Documentation/kube-flannel.yml#L145-L159) a couple of files for the containers to use.
* The `initContainer` named [`install-cni`](https://github.com/coreos/flannel/blob/c5d10c8b16d7c43bfa6e8408673c6d95404bd807/Documentation/kube-flannel.yml#L105-L118) that is run before all other containers should set up the flannel config using a trivial `cp -f`.
* The `container` named [`kube-flannel`](https://github.com/coreos/flannel/blob/c5d10c8b16d7c43bfa6e8408673c6d95404bd807/Documentation/kube-flannel.yml#L119-L144) then launches flannel with args.

Furthermore, the Docker image itself is built to contain a few files in specific dirs, pull updates from the web with `apk`, and define environment variables:

```
$ docker history quay.io/coreos/flannel:v0.10.0-amd64 --no-trunc
IMAGE                                                                     CREATED             CREATED BY                                                                                                           SIZE                COMMENT
sha256:f0fad859c909baef1b038ef8d2f6e76fc252e25a3d9af37b82ce70623fb7cd6f   7 months ago        /bin/sh -c #(nop)  ENTRYPOINT ["/opt/bin/flanneld"]                                                                  0B                  
<missing>                                                                 7 months ago        /bin/sh -c #(nop) COPY file:8f67962c12e58671bee18c93535885714647b91271193b7dc5832188905ec9d1 in /opt/bin/            2.14kB              
<missing>                                                                 7 months ago        /bin/sh -c #(nop) COPY file:89b8aa8abb1c9d8a3e8b4d5b84337bb71b1abff0e9691a5d5ffb4ee885215126 in /opt/bin/flanneld    36.3MB              
<missing>                                                                 7 months ago        /bin/sh -c apk add wireguard-tools --no-cache --repository http://dl-cdn.alpinelinux.org/alpine/edge/testing         148kB               
<missing>                                                                 7 months ago        /bin/sh -c apk add --no-cache iproute2 net-tools ca-certificates iptables && update-ca-certificates                  3.97MB              
<missing>                                                                 7 months ago        /bin/sh -c #(nop)  ENV FLANNEL_ARCH=amd64                                                                            0B                  
<missing>                                                                 7 months ago        /bin/sh -c #(nop)  LABEL maintainer=Tom Denham <tom@tigera.io>                                                       0B                  
<missing>                                                                 7 months ago        /bin/sh -c #(nop)  CMD ["/bin/sh"]                                                                                   0B                  
<missing>                                                                 7 months ago        /bin/sh -c #(nop) ADD file:093f0723fa46f6cdbd6f7bd146448bb70ecce54254c35701feeceb956414622f in /                     4.15MB
```

If you go and `kubectl describe` pods instantiated by the `kube-flannel-ds-amd64` config, nodes where the `initContainer` completed its setup will show the `kube-flannel` container running. Where the `initContainer` failed, `kube-flannel` can't run obviously; the environment, mounts etc. are identical between successful and failed instances.

My next attempt will be to deploy the `initContainer` on a node but `kubectl exec -ti` into it and run the setup commands by hand.

**Comment by junekiwi** [comment]
We're not using Flannel anymore (but Calico).
