### ISSUE TITLE
DRY and use Kubernetes/Python bindings instead of `Popen` and custom shell scripts

### ISSUE THREAD

**Issue by aaaaalbert** [EdgeNet-project/edgenet-legacy-2024#6]
We are accumulating [calls to custom shell scripts](https://github.com/aaaaalbert/sundew-one/blob/714e3adcaac2b3d216931ee33a344be8168e6cbb/daemons/user-daemon.py#L25-L34) (which in turn call into `kubectl` mostly), and most of the code is copied-and-pasted. Let's aim to not repeat ourselves ("DRY principle"), and also see if we can make use of the existing projects to provide Python bindings for Kubernetes.

Quick finds:
* https://github.com/4Catalyzer/pykubectl is a simple, also `Popen`-based bridge to `kubectl`.
* https://github.com/mnubo/kubernetes-py/ looks promising

**Comment by tashabits** [comment]
Factored the code for Popen calls ( 5fb5dd730105753fdf7e1ebd055c33b4f0e6a230 )
