### ISSUE TITLE
The role of the token in headnode/assets/templates/email/web-token.html

### ISSUE THREAD

**Issue by timur-friedman** [EdgeNet-project/edgenet-legacy-2024#61]
Looking at web-token.html as a file in isolation, without knowing how the e-mail is triggered, I'm uncertain about the role of the token that is being sent to the user. Is it their personal token or is it the public token? Similarly with the associated kubeconfig file. If it is a personal token, we'll want to accompany the e-mail with advice about keeping the token private.

**Comment by bsenel** [comment]
This is a prototype work for login activity. When a user signs in with the credentials of username and password, this controller creates a particular and temporary service account (TTL is 1h and extendable) dedicated to that user. So, the token in this file is a personal token related to that temporary service account.

**Comment by bsenel** [comment]
I am closing the issue due to the removal of password management by EdgeNet extensions.
