### ISSUE TITLE
Direct login for headnode/assets/templates/email/web-token.html

### ISSUE THREAD

**Issue by timur-friedman** [EdgeNet-project/edgenet-legacy-2024#63]
Am I correct in thinking that appending /login/{{.Token}} to the headnode URL is the most direct way to sign in to the Dashboard using the token? If so, I propose that we offer this URL directly as a clickable link.

**Comment by bsenel** [comment]
That was for the portal that Ciro is developing. It will be replaced as soon as the EdgeNet Portal, an extension of Kubernetes Dashboard, is ready.

**Comment by bsenel** [comment]
I am closing the issue due to the removal of password management by EdgeNet extensions. The file doesn't exist anymore.
