### ISSUE TITLE
Replace "Tutorials" with "Support" on the website

### ISSUE THREAD

**Issue by timur-friedman** [EdgeNet-project/edgenet-legacy-2024#64]
I recommend replacing the main category of "Tutorials" with "Support" on the website. This is broader, as it includes the notion of a user guide for very simple things like signing up for an account, which should not require something as elaborate as a tutorial. I have changed the title in the menu, and am changing the e-mails, but I have not changed the term "tutorial" to "support" globally.

**Comment by bsenel** [comment]
The tutorial term has globally been changed as support on the website.
