### ISSUE TITLE
Replace "API Docs" with "Code" in the website main menu

### ISSUE THREAD

**Issue by timur-friedman** [EdgeNet-project/edgenet-legacy-2024#65]
Currently, the main menu item "API Docs" takes the user away from the website. From a UI point of view, I think it's better if the main menu items keep the user on the website, so they don't unexpectedly leave the website, and have to hit the "back" button in order to keep navigating the site. The "Login" item is different, as it is clearly set apart by its design. I have changed the menu to add a "Code" item, but we'll still need to set up a corresponding page that will say a bit about the code and point the user to both our GitHub repository and our Postman documentation.

**Comment by bsenel** [comment]
Now we have a basic **code page** including buttons to access out our GitHub repository and our Postman documentation.
