### ISSUE TITLE
Our HTML comments are generating validation errors

### ISSUE THREAD

**Issue by timur-friedman** [EdgeNet-project/edgenet-legacy-2024#67]
Each comment that we use for visual separation of sections in the HTML source of a web page generates dozens of validation errors, one for each pair of hyphens:

          

The errors are: "The document is not mappable to XML 1.0 due to two consecutive hyphens in a comment."

I'm replacing these comments with comments of this form:

**Comment by bsenel** [comment]
You are right and hyphens have been changed as you suggested. Additionally, I also updated all the pages to pass the validation.
