### ISSUE TITLE
Node contribution tutorial

### ISSUE THREAD

**Issue by timur-friedman** [EdgeNet-project/edgenet-legacy-2024#71]
As an authorized User, I would like a tutorial on how to go about making a node contribution.

- [x] edit the tutorial (@timur-friedman)
- [x] proof read the tutorial for technical correctness (@bsenel) 
- [x] push the changes to the website (@bsenel)

**Comment by bsenel** [comment]
I did not notice any technical problems in the tutorial, so I pushed the changes on the website.

**Comment by bsenel** [comment]
Update the tutorial according to feedback provided by Marco Simioni from University College Dublin.
