### ISSUE TITLE
Agree on web presence

### ISSUE THREAD

**Issue by timur-friedman** [EdgeNet-project/edgenet-legacy-2024#75]
Verify that our web presence should consist of: (1) public website for users, (2) support section for users on the GitHub, (3) web console for non-Kubernetes users, (4) tutorial section on the GitHub, containing specific tutorials for different events, (5) development documents on GitHub, outlining the architecture, (6) source code on the GitHub

**Comment by timur-friedman** [comment]
Agreed and ADR created

**Comment by timur-friedman** [comment]
@bsenel do we still have a code documentation site?

**Comment by bsenel** [comment]
I am not sure what you mean by a code documentation site. However, there is a code page on the website at http://edge-net.org/code.html including an API documentation link to https://documenter.getpostman.com/view/7656709/SzYT4gRL?version=latest. GitHub pages still can be used for different purposes. I hope this answers your question.

**Comment by timur-friedman** [comment]
Thank you, @bsenel , this is exactly what I meant! Our web presence includes the Postman site. I will add it to the ADR.

**Comment by timur-friedman** [comment]
Will create a new issue for code documentation, which is still an outstanding question.
