### ISSUE TITLE
Add node map, table, and numbers back to the website

### ISSUE THREAD

**Issue by timur-friedman** [EdgeNet-project/edgenet-legacy-2024#78]
The pages index.html and about.html both had non-working maps and tables purporting to describe the number of nodes up and running on EdgeNet. 

The numbers were inconsistent in the text, and the map and table were blank, tending to give the impression of a broken site rather than a functional testbed. 

Once we can get them working, they'll give the opposite impression, of a well-running testbed. Until such time, they've been commented out.

See:

https://github.com/EdgeNet-project/edgenet/blob/bb0943cc13cdb1be894bc42cd9bd6b8136372de1/website/index.html#L132-L172

and

https://github.com/EdgeNet-project/edgenet/blob/bb0943cc13cdb1be894bc42cd9bd6b8136372de1/website/about.html#L86-L152

**Comment by bsenel** [comment]
This is caused by an SSL problem on the head node. Additionally, as of today, we have the same problem with the Kubernetes dashboard. I added Ciro to assignees.

**Comment by timur-friedman** [comment]
If it is possible to remove the node map, table, and numbers from the website while they are not working, let's please make that a priority. I already commented out the HTML in the release-1.0 code, so it just needs to be pushed to the master branch and integrated into the working website.

While it's fine to not have certain features, in my opinion it is extremely damaging to have broken features, and we should be sure to remove broken features from the public website as fast as possible. They are a sure way to give users and others the impression of a system that does not work.

**Comment by bsenel** [comment]
They pulled out from the website until we make them work by providing an SSL. So, the website in production doesn't include those.

**Comment by bsenel** [comment]
@timur-friedman, I created a CNAME record for https://apiserver.edge-net.org/ by following Ciro's pattern, generated an SSL certificate and set a proxy pass to the API server. Everything seems to be in order, so, I put them back on the [website](https://www.edge-net.org/). @cscognamiglio, it would be great if you can check the nginx configuration out when you have time for it.
