### ISSUE TITLE
Fix HTML validation errors: bad attribute names

### ISSUE THREAD

**Issue by timur-friedman** [EdgeNet-project/edgenet-legacy-2024#81]
We get the following three HTML validation errors 

> Bad value msapplication-TileColor for attribute name on element meta: Keyword msapplication-tilecolor is not registered.

> Bad value msapplication-TileImage for attribute name on element meta: Keyword msapplication-tileimage is not registered.

> Bad value theme-color for attribute name on element meta: Keyword theme-color is not registered.

in the following code:

https://github.com/EdgeNet-project/edgenet/blob/92c44bb82dbecff5def9ea98f4f52fe4ca411427/website/index.html#L29-L31

https://github.com/EdgeNet-project/edgenet/blob/92c44bb82dbecff5def9ea98f4f52fe4ca411427/website/features.html#L27-L29

https://github.com/EdgeNet-project/edgenet/blob/92c44bb82dbecff5def9ea98f4f52fe4ca411427/website/code.html#L29-L31

https://github.com/EdgeNet-project/edgenet/blob/92c44bb82dbecff5def9ea98f4f52fe4ca411427/website/about.html#L29-L31

https://github.com/EdgeNet-project/edgenet/blob/92c44bb82dbecff5def9ea98f4f52fe4ca411427/website/support.html#L29-L31

**Comment by bsenel** [comment]
Duplicated #80, the issue is closed.
