### ISSUE TITLE
Provide a certificate for the website

### ISSUE THREAD

**Issue by timur-friedman** [EdgeNet-project/edgenet-legacy-2024#82]
Provide a LetsEncrypt certificate for the edge-net.org website.

Allow the website to be accessed via HTTPS.

**Comment by cscognamiglio** [comment]
I configured two certificates for:

- The website at https://edge-net.org
- The Kubernetes Dashboard at https://dashboard.edge-net.org

Also there is an automatic redirection from http -> https for both.
Certificates will be renewed automatically.
