### ISSUE TITLE
EdgeNetFlow take port 80

### ISSUE THREAD

**Issue by timur-friedman** [EdgeNet-project/edgenet-legacy-2024#83]
Enable a web server on port 80 on each node, so as to identify the node as an EdgeNet node.

This is a required part of an eventual EdgeNetFlow service, and can be implemented to begin with independently of any other aspects of the service.

**Comment by junekiwi** [comment]
@bsenel @timur-friedman do we still want to do this?

If so it's quite easy, we can run a DS serving a static webpage on port 80.
