### ISSUE TITLE
EdgeNetFlow per-pod packet capture research

### ISSUE THREAD

**Issue by timur-friedman** [EdgeNet-project/edgenet-legacy-2024#84]
Research the options for per-pod packet capture.

We want to do NetFlow-type gathering of the five-tuples of every packet that enters or leaves a node, associating each five-tuple with the pod that sent or received it.

This is a prerequisite to building a EdgeNetFlow service. We need to research what options already exist for this sort of monitoring.

**Comment by bsenel** [comment]
As EdgeNet's current CNI, [VMware's Antrea](https://antrea.io/docs/v1.4.0/docs/network-flow-visibility/), provides this feature, I close this issue.
