### ISSUE TITLE
Design a leaderboard display

### ISSUE THREAD

**Issue by timur-friedman** [EdgeNet-project/edgenet-legacy-2024#85]
We'd like to encourage people to contribute nodes to EdgeNet, and one way to do this is through leaderboards, showing who has contributed successfully to the platform.

The task here is to come up with a preliminary design of what a leaderboard display might look like and how it might work. It could also include some ideas for the technology that would be used to display the leaderboard.

**Comment by JustinCappos** [comment]
We can do this, but having it too early may make our adoption look weak.  We really haven't opened the floodgates for node contributions yet...
